<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pokemon;

class PokemonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pokemon::updateOrCreate(['id' => 1], ['name' => 'Bulbasaur', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 2], ['name' => 'Ivysaur', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 3], ['name' => 'Venusaur', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 4], ['name' => 'Charmander', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 5], ['name' => 'Charmeleon', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 6], ['name' => 'Charizard', 'primary' => 'Fire', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 7], ['name' => 'Squirtle', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 8], ['name' => 'Wartortle', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 9], ['name' => 'Blastoise', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 10], ['name' => 'Caterpie', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 11], ['name' => 'Metapod', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 12], ['name' => 'Butterfree', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 13], ['name' => 'Weedle', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 14], ['name' => 'Kakuna', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 15], ['name' => 'Beedrill', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 16], ['name' => 'Pidgey', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 17], ['name' => 'Pidgeotto', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 18], ['name' => 'Pidgeot', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 19], ['name' => 'Rattata', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 19.1], ['name' => 'Rattata', 'primary' => 'Dark', 'secondary' => 'Normal', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 20], ['name' => 'Raticate', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 20.1], ['name' => 'Raticate', 'primary' => 'Dark', 'secondary' => 'Normal', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 21], ['name' => 'Spearow', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 22], ['name' => 'Fearow', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 23], ['name' => 'Ekans', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 24], ['name' => 'Arbok', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 25], ['name' => 'Pikachu', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 26], ['name' => 'Raichu', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 26.1], ['name' => 'Raichu', 'primary' => 'Electric', 'secondary' => 'Psychic', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 27], ['name' => 'Sandshrew', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 27.1], ['name' => 'Sandshrew', 'primary' => 'Ice', 'secondary' => 'Steel', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 28], ['name' => 'Sandslash', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 28.1], ['name' => 'Sandslash', 'primary' => 'Ice', 'secondary' => 'Steel', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 29], ['name' => 'Nidoran♀', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 30], ['name' => 'Nidorina', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 31], ['name' => 'Nidoqueen', 'primary' => 'Poison', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 32], ['name' => 'Nidoran♂', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 33], ['name' => 'Nidorino', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 34], ['name' => 'Nidoking', 'primary' => 'Poison', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 35], ['name' => 'Clefairy', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 36], ['name' => 'Clefable', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 37], ['name' => 'Vulpix', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 37.1], ['name' => 'Vulpix', 'primary' => 'Ice', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 38], ['name' => 'Ninetales', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 38.1], ['name' => 'Ninetales', 'primary' => 'Ice', 'secondary' => 'Fairy', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 39], ['name' => 'Jigglypuff', 'primary' => 'Normal', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 40], ['name' => 'Wigglytuff', 'primary' => 'Normal', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 41], ['name' => 'Zubat', 'primary' => 'Poison', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 42], ['name' => 'Golbat', 'primary' => 'Poison', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 43], ['name' => 'Oddish', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 44], ['name' => 'Gloom', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 45], ['name' => 'Vileplume', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 46], ['name' => 'Paras', 'primary' => 'Bug', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 47], ['name' => 'Parasect', 'primary' => 'Bug', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 48], ['name' => 'Venonat', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 49], ['name' => 'Venomoth', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 50], ['name' => 'Diglett', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 50.1], ['name' => 'Diglett', 'primary' => 'Ground', 'secondary' => 'Steel', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 51], ['name' => 'Dugtrio', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 51.1], ['name' => 'Dugtrio', 'primary' => 'Ground', 'secondary' => 'Steel', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 52], ['name' => 'Meowth', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 52.1], ['name' => 'Meowth', 'primary' => 'Dark', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 53], ['name' => 'Persian', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 53.1], ['name' => 'Persian', 'primary' => 'Dark', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 54], ['name' => 'Psyduck', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 55], ['name' => 'Golduck', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 56], ['name' => 'Mankey', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 57], ['name' => 'Primeape', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 58], ['name' => 'Growlithe', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 59], ['name' => 'Arcanine', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 60], ['name' => 'Poliwag', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 61], ['name' => 'Poliwhirl', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 62], ['name' => 'Poliwrath', 'primary' => 'Water', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 63], ['name' => 'Abra', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 64], ['name' => 'Kadabra', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 65], ['name' => 'Alakazam', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 66], ['name' => 'Machop', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 67], ['name' => 'Machoke', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 68], ['name' => 'Machamp', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 69], ['name' => 'Bellsprout', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 70], ['name' => 'Weepinbell', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 71], ['name' => 'Victreebel', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 72], ['name' => 'Tentacool', 'primary' => 'Water', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 73], ['name' => 'Tentacruel', 'primary' => 'Water', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 74], ['name' => 'Geodude', 'primary' => 'Rock', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 74.1], ['name' => 'Geodude', 'primary' => 'Rock', 'secondary' => 'Electric', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 75], ['name' => 'Graveler', 'primary' => 'Rock', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 75.1], ['name' => 'Graveler', 'primary' => 'Rock', 'secondary' => 'Electric', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 76], ['name' => 'Golem', 'primary' => 'Rock', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 76.1], ['name' => 'Golem', 'primary' => 'Rock', 'secondary' => 'Electric', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 77], ['name' => 'Ponyta', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 78], ['name' => 'Rapidash', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 79], ['name' => 'Slowpoke', 'primary' => 'Water', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 80], ['name' => 'Slowbro', 'primary' => 'Water', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 81], ['name' => 'Magnemite', 'primary' => 'Electric', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 82], ['name' => 'Magneton', 'primary' => 'Electric', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 83], ['name' => 'Farfetch\'d', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 84], ['name' => 'Doduo', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 85], ['name' => 'Dodrio', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 86], ['name' => 'Seel', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 87], ['name' => 'Dewgong', 'primary' => 'Water', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 88], ['name' => 'Grimer', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 88.1], ['name' => 'Grimer', 'primary' => 'Poison', 'secondary' => 'Dark', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 89], ['name' => 'Muk', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 89.1], ['name' => 'Muk', 'primary' => 'Poison', 'secondary' => 'Dark', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 90], ['name' => 'Shellder', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 91], ['name' => 'Cloyster', 'primary' => 'Water', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 92], ['name' => 'Gastly', 'primary' => 'Ghost', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 93], ['name' => 'Haunter', 'primary' => 'Ghost', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 94], ['name' => 'Gengar', 'primary' => 'Ghost', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 95], ['name' => 'Onix', 'primary' => 'Rock', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 96], ['name' => 'Drowzee', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 97], ['name' => 'Hypno', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 98], ['name' => 'Krabby', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 99], ['name' => 'Kingler', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 100], ['name' => 'Voltorb', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 101], ['name' => 'Electrode', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 102], ['name' => 'Exeggcute', 'primary' => 'Grass', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 103], ['name' => 'Exeggutor', 'primary' => 'Grass', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 103.1], ['name' => 'Exeggutor', 'primary' => 'Grass', 'secondary' => 'Dragon', 'variant' => 'Alolan',]);
        Pokemon::updateOrCreate(['id' => 104], ['name' => 'Cubone', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 105], ['name' => 'Marowak', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 105], ['name' => 'Marowak', 'primary' => 'Fire', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 106], ['name' => 'Hitmonlee', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 107], ['name' => 'Hitmonchan', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 108], ['name' => 'Lickitung', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 109], ['name' => 'Koffing', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 110], ['name' => 'Weezing', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 111], ['name' => 'Rhyhorn', 'primary' => 'Ground', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 112], ['name' => 'Rhydon', 'primary' => 'Ground', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 113], ['name' => 'Chansey', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 114], ['name' => 'Tangela', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 115], ['name' => 'Kangaskhan', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 116], ['name' => 'Horsea', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 117], ['name' => 'Seadra', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 118], ['name' => 'Goldeen', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 119], ['name' => 'Seaking', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 120], ['name' => 'Staryu', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 121], ['name' => 'Starmie', 'primary' => 'Water', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 122], ['name' => 'Mr. Mime', 'primary' => 'Psychic', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 123], ['name' => 'Scyther', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 124], ['name' => 'Jynx', 'primary' => 'Ice', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 125], ['name' => 'Electabuzz', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 126], ['name' => 'Magmar', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 127], ['name' => 'Pinsir', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 128], ['name' => 'Tauros', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 129], ['name' => 'Magikarp', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 130], ['name' => 'Gyarados', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 131], ['name' => 'Lapras', 'primary' => 'Water', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 132], ['name' => 'Ditto', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 133], ['name' => 'Eevee', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 134], ['name' => 'Vaporeon', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 135], ['name' => 'Jolteon', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 136], ['name' => 'Flareon', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 137], ['name' => 'Porygon', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 138], ['name' => 'Omanyte', 'primary' => 'Rock', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 139], ['name' => 'Omastar', 'primary' => 'Rock', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 140], ['name' => 'Kabuto', 'primary' => 'Rock', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 141], ['name' => 'Kabutops', 'primary' => 'Rock', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 142], ['name' => 'Aerodactyl', 'primary' => 'Rock', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 143], ['name' => 'Snorlax', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 144], ['name' => 'Articuno', 'primary' => 'Ice', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 145], ['name' => 'Zapdos', 'primary' => 'Electric', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 146], ['name' => 'Moltres', 'primary' => 'Fire', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 147], ['name' => 'Dratini', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 148], ['name' => 'Dragonair', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 149], ['name' => 'Dragonite', 'primary' => 'Dragon', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 150], ['name' => 'Mewtwo', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 151], ['name' => 'Mew', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 152], ['name' => 'Chikorita', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 153], ['name' => 'Bayleef', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 154], ['name' => 'Meganium', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 155], ['name' => 'Cyndaquil', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 156], ['name' => 'Quilava', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 157], ['name' => 'Typhlosion', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 158], ['name' => 'Totodile', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 159], ['name' => 'Croconaw', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 160], ['name' => 'Feraligatr', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 161], ['name' => 'Sentret', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 162], ['name' => 'Furret', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 163], ['name' => 'Hoothoot', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 164], ['name' => 'Noctowl', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 165], ['name' => 'Ledyba', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 166], ['name' => 'Ledian', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 167], ['name' => 'Spinarak', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 168], ['name' => 'Ariados', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 169], ['name' => 'Crobat', 'primary' => 'Poison', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 170], ['name' => 'Chinchou', 'primary' => 'Water', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 171], ['name' => 'Lanturn', 'primary' => 'Water', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 172], ['name' => 'Pichu', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 173], ['name' => 'Cleffa', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 174], ['name' => 'Igglybuff', 'primary' => 'Normal', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 175], ['name' => 'Togepi', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 176], ['name' => 'Togetic', 'primary' => 'Fairy', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 177], ['name' => 'Natu', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 178], ['name' => 'Xatu', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 179], ['name' => 'Mareep', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 180], ['name' => 'Flaaffy', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 181], ['name' => 'Ampharos', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 182], ['name' => 'Bellossom', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 183], ['name' => 'Marill', 'primary' => 'Water', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 184], ['name' => 'Azumarill', 'primary' => 'Water', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 185], ['name' => 'Sudowoodo', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 186], ['name' => 'Politoed', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 187], ['name' => 'Hoppip', 'primary' => 'Grass', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 188], ['name' => 'Skiploom', 'primary' => 'Grass', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 189], ['name' => 'Jumpluff', 'primary' => 'Grass', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 190], ['name' => 'Aipom', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 191], ['name' => 'Sunkern', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 192], ['name' => 'Sunflora', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 193], ['name' => 'Yanma', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 194], ['name' => 'Wooper', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 195], ['name' => 'Quagsire', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 196], ['name' => 'Espeon', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 197], ['name' => 'Umbreon', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 198], ['name' => 'Murkrow', 'primary' => 'Dark', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 199], ['name' => 'Slowking', 'primary' => 'Water', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 200], ['name' => 'Misdreavus', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 201], ['name' => 'Unown', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 202], ['name' => 'Wobbuffet', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 203], ['name' => 'Girafarig', 'primary' => 'Normal', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 204], ['name' => 'Pineco', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 205], ['name' => 'Forretress', 'primary' => 'Bug', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 206], ['name' => 'Dunsparce', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 207], ['name' => 'Gligar', 'primary' => 'Ground', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 208], ['name' => 'Steelix', 'primary' => 'Steel', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 209], ['name' => 'Snubbull', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 210], ['name' => 'Granbull', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 211], ['name' => 'Qwilfish', 'primary' => 'Water', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 212], ['name' => 'Scizor', 'primary' => 'Bug', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 213], ['name' => 'Shuckle', 'primary' => 'Bug', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 214], ['name' => 'Heracross', 'primary' => 'Bug', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 215], ['name' => 'Sneasel', 'primary' => 'Dark', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 216], ['name' => 'Teddiursa', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 217], ['name' => 'Ursaring', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 218], ['name' => 'Slugma', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 219], ['name' => 'Magcargo', 'primary' => 'Fire', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 220], ['name' => 'Swinub', 'primary' => 'Ice', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 221], ['name' => 'Piloswine', 'primary' => 'Ice', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 222], ['name' => 'Corsola', 'primary' => 'Water', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 223], ['name' => 'Remoraid', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 224], ['name' => 'Octillery', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 225], ['name' => 'Delibird', 'primary' => 'Ice', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 226], ['name' => 'Mantine', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 227], ['name' => 'Skarmory', 'primary' => 'Steel', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 228], ['name' => 'Houndour', 'primary' => 'Dark', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 229], ['name' => 'Houndoom', 'primary' => 'Dark', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 230], ['name' => 'Kingdra', 'primary' => 'Water', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 231], ['name' => 'Phanpy', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 232], ['name' => 'Donphan', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 233], ['name' => 'Porygon2', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 234], ['name' => 'Stantler', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 235], ['name' => 'Smeargle', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 236], ['name' => 'Tyrogue', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 237], ['name' => 'Hitmontop', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 238], ['name' => 'Smoochum', 'primary' => 'Ice', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 239], ['name' => 'Elekid', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 240], ['name' => 'Magby', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 241], ['name' => 'Miltank', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 242], ['name' => 'Blissey', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 243], ['name' => 'Raikou', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 244], ['name' => 'Entei', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 245], ['name' => 'Suicune', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 246], ['name' => 'Larvitar', 'primary' => 'Rock', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 247], ['name' => 'Pupitar', 'primary' => 'Rock', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 248], ['name' => 'Tyranitar', 'primary' => 'Rock', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 249], ['name' => 'Lugia', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 250], ['name' => 'Ho-Oh', 'primary' => 'Fire', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 251], ['name' => 'Celebi', 'primary' => 'Psychic', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 252], ['name' => 'Treecko', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 253], ['name' => 'Grovyle', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 254], ['name' => 'Sceptile', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 255], ['name' => 'Torchic', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 256], ['name' => 'Combusken', 'primary' => 'Fire', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 257], ['name' => 'Blaziken', 'primary' => 'Fire', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 258], ['name' => 'Mudkip', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 259], ['name' => 'Marshtomp', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 260], ['name' => 'Swampert', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 261], ['name' => 'Poochyena', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 262], ['name' => 'Mightyena', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 263], ['name' => 'Zigzagoon', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 264], ['name' => 'Linoone', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 265], ['name' => 'Wurmple', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 266], ['name' => 'Silcoon', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 267], ['name' => 'Beautifly', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 268], ['name' => 'Cascoon', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 269], ['name' => 'Dustox', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 270], ['name' => 'Lotad', 'primary' => 'Water', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 271], ['name' => 'Lombre', 'primary' => 'Water', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 272], ['name' => 'Ludicolo', 'primary' => 'Water', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 273], ['name' => 'Seedot', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 274], ['name' => 'Nuzleaf', 'primary' => 'Grass', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 275], ['name' => 'Shiftry', 'primary' => 'Grass', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 276], ['name' => 'Taillow', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 277], ['name' => 'Swellow', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 278], ['name' => 'Wingull', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 279], ['name' => 'Pelipper', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 280], ['name' => 'Ralts', 'primary' => 'Psychic', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 281], ['name' => 'Kirlia', 'primary' => 'Psychic', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 282], ['name' => 'Gardevoir', 'primary' => 'Psychic', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 283], ['name' => 'Surskit', 'primary' => 'Bug', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 284], ['name' => 'Masquerain', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 285], ['name' => 'Shroomish', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 286], ['name' => 'Breloom', 'primary' => 'Grass', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 287], ['name' => 'Slakoth', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 288], ['name' => 'Vigoroth', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 289], ['name' => 'Slaking', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 290], ['name' => 'Nincada', 'primary' => 'Bug', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 291], ['name' => 'Ninjask', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 292], ['name' => 'Shedinja', 'primary' => 'Bug', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 293], ['name' => 'Whismur', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 294], ['name' => 'Loudred', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 295], ['name' => 'Exploud', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 296], ['name' => 'Makuhita', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 297], ['name' => 'Hariyama', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 298], ['name' => 'Azurill', 'primary' => 'Normal', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 299], ['name' => 'Nosepass', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 300], ['name' => 'Skitty', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 301], ['name' => 'Delcatty', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 302], ['name' => 'Sableye', 'primary' => 'Dark', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 303], ['name' => 'Mawile', 'primary' => 'Steel', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 304], ['name' => 'Aron', 'primary' => 'Steel', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 305], ['name' => 'Lairon', 'primary' => 'Steel', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 306], ['name' => 'Aggron', 'primary' => 'Steel', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 307], ['name' => 'Meditite', 'primary' => 'Fighting', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 308], ['name' => 'Medicham', 'primary' => 'Fighting', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 309], ['name' => 'Electrike', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 310], ['name' => 'Manectric', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 311], ['name' => 'Plusle', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 312], ['name' => 'Minun', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 313], ['name' => 'Volbeat', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 314], ['name' => 'Illumise', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 315], ['name' => 'Roselia', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 316], ['name' => 'Gulpin', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 317], ['name' => 'Swalot', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 318], ['name' => 'Carvanha', 'primary' => 'Water', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 319], ['name' => 'Sharpedo', 'primary' => 'Water', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 320], ['name' => 'Wailmer', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 321], ['name' => 'Wailord', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 322], ['name' => 'Numel', 'primary' => 'Fire', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 323], ['name' => 'Camerupt', 'primary' => 'Fire', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 324], ['name' => 'Torkoal', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 325], ['name' => 'Spoink', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 326], ['name' => 'Grumpig', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 327], ['name' => 'Spinda', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 328], ['name' => 'Trapinch', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 329], ['name' => 'Vibrava', 'primary' => 'Ground', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 330], ['name' => 'Flygon', 'primary' => 'Ground', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 331], ['name' => 'Cacnea', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 332], ['name' => 'Cacturne', 'primary' => 'Grass', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 333], ['name' => 'Swablu', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 334], ['name' => 'Altaria', 'primary' => 'Dragon', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 335], ['name' => 'Zangoose', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 336], ['name' => 'Seviper', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 337], ['name' => 'Lunatone', 'primary' => 'Rock', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 338], ['name' => 'Solrock', 'primary' => 'Rock', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 339], ['name' => 'Barboach', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 340], ['name' => 'Whiscash', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 341], ['name' => 'Corphish', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 342], ['name' => 'Crawdaunt', 'primary' => 'Water', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 343], ['name' => 'Baltoy', 'primary' => 'Ground', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 344], ['name' => 'Claydol', 'primary' => 'Ground', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 345], ['name' => 'Lileep', 'primary' => 'Rock', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 346], ['name' => 'Cradily', 'primary' => 'Rock', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 347], ['name' => 'Anorith', 'primary' => 'Rock', 'secondary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 348], ['name' => 'Armaldo', 'primary' => 'Rock', 'secondary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 349], ['name' => 'Feebas', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 350], ['name' => 'Milotic', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 351], ['name' => 'Castform', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 352], ['name' => 'Kecleon', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 353], ['name' => 'Shuppet', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 354], ['name' => 'Banette', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 355], ['name' => 'Duskull', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 356], ['name' => 'Dusclops', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 357], ['name' => 'Tropius', 'primary' => 'Grass', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 358], ['name' => 'Chimecho', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 359], ['name' => 'Absol', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 360], ['name' => 'Wynaut', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 361], ['name' => 'Snorunt', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 362], ['name' => 'Glalie', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 363], ['name' => 'Spheal', 'primary' => 'Ice', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 364], ['name' => 'Sealeo', 'primary' => 'Ice', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 365], ['name' => 'Walrein', 'primary' => 'Ice', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 366], ['name' => 'Clamperl', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 367], ['name' => 'Huntail', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 368], ['name' => 'Gorebyss', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 369], ['name' => 'Relicanth', 'primary' => 'Water', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 370], ['name' => 'Luvdisc', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 371], ['name' => 'Bagon', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 372], ['name' => 'Shelgon', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 373], ['name' => 'Salamence', 'primary' => 'Dragon', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 374], ['name' => 'Beldum', 'primary' => 'Steel', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 375], ['name' => 'Metang', 'primary' => 'Steel', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 376], ['name' => 'Metagross', 'primary' => 'Steel', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 377], ['name' => 'Regirock', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 378], ['name' => 'Regice', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 379], ['name' => 'Registeel', 'primary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 380], ['name' => 'Latias', 'primary' => 'Dragon', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 381], ['name' => 'Latios', 'primary' => 'Dragon', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 382], ['name' => 'Kyogre', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 383], ['name' => 'Groudon', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 384], ['name' => 'Rayquaza', 'primary' => 'Dragon', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 385], ['name' => 'Jirachi', 'primary' => 'Steel', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 386], ['name' => 'Deoxys', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 387], ['name' => 'Turtwig', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 388], ['name' => 'Grotle', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 389], ['name' => 'Torterra', 'primary' => 'Grass', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 390], ['name' => 'Chimchar', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 391], ['name' => 'Monferno', 'primary' => 'Fire', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 392], ['name' => 'Infernape', 'primary' => 'Fire', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 393], ['name' => 'Piplup', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 394], ['name' => 'Prinplup', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 395], ['name' => 'Empoleon', 'primary' => 'Water', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 396], ['name' => 'Starly', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 397], ['name' => 'Staravia', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 398], ['name' => 'Staraptor', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 399], ['name' => 'Bidoof', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 400], ['name' => 'Bibarel', 'primary' => 'Normal', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 401], ['name' => 'Kricketot', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 402], ['name' => 'Kricketune', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 403], ['name' => 'Shinx', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 404], ['name' => 'Luxio', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 405], ['name' => 'Luxray', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 406], ['name' => 'Budew', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 407], ['name' => 'Roserade', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 408], ['name' => 'Cranidos', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 409], ['name' => 'Rampardos', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 410], ['name' => 'Shieldon', 'primary' => 'Rock', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 411], ['name' => 'Bastiodon', 'primary' => 'Rock', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 412], ['name' => 'Burmy', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 413], ['name' => 'Wormadam', 'primary' => 'Bug', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 414], ['name' => 'Mothim', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 415], ['name' => 'Combee', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 416], ['name' => 'Vespiquen', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 417], ['name' => 'Pachirisu', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 418], ['name' => 'Buizel', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 419], ['name' => 'Floatzel', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 420], ['name' => 'Cherubi', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 421], ['name' => 'Cherrim', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 422], ['name' => 'Shellos', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 423], ['name' => 'Gastrodon', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 424], ['name' => 'Ambipom', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 425], ['name' => 'Drifloon', 'primary' => 'Ghost', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 426], ['name' => 'Drifblim', 'primary' => 'Ghost', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 427], ['name' => 'Buneary', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 428], ['name' => 'Lopunny', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 429], ['name' => 'Mismagius', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 430], ['name' => 'Honchkrow', 'primary' => 'Dark', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 431], ['name' => 'Glameow', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 432], ['name' => 'Purugly', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 433], ['name' => 'Chingling', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 434], ['name' => 'Stunky', 'primary' => 'Poison', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 435], ['name' => 'Skuntank', 'primary' => 'Poison', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 436], ['name' => 'Bronzor', 'primary' => 'Steel', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 437], ['name' => 'Bronzong', 'primary' => 'Steel', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 438], ['name' => 'Bonsly', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 439], ['name' => 'Mime Jr.', 'primary' => 'Psychic', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 440], ['name' => 'Happiny', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 441], ['name' => 'Chatot', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 442], ['name' => 'Spiritomb', 'primary' => 'Ghost', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 443], ['name' => 'Gible', 'primary' => 'Dragon', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 444], ['name' => 'Gabite', 'primary' => 'Dragon', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 445], ['name' => 'Garchomp', 'primary' => 'Dragon', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 446], ['name' => 'Munchlax', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 447], ['name' => 'Riolu', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 448], ['name' => 'Lucario', 'primary' => 'Fighting', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 449], ['name' => 'Hippopotas', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 450], ['name' => 'Hippowdon', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 451], ['name' => 'Skorupi', 'primary' => 'Poison', 'secondary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 452], ['name' => 'Drapion', 'primary' => 'Poison', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 453], ['name' => 'Croagunk', 'primary' => 'Poison', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 454], ['name' => 'Toxicroak', 'primary' => 'Poison', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 455], ['name' => 'Carnivine', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 456], ['name' => 'Finneon', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 457], ['name' => 'Lumineon', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 458], ['name' => 'Mantyke', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 459], ['name' => 'Snover', 'primary' => 'Grass', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 460], ['name' => 'Abomasnow', 'primary' => 'Grass', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 461], ['name' => 'Weavile', 'primary' => 'Dark', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 462], ['name' => 'Magnezone', 'primary' => 'Electric', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 463], ['name' => 'Lickilicky', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 464], ['name' => 'Rhyperior', 'primary' => 'Ground', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 465], ['name' => 'Tangrowth', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 466], ['name' => 'Electivire', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 467], ['name' => 'Magmortar', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 468], ['name' => 'Togekiss', 'primary' => 'Fairy', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 469], ['name' => 'Yanmega', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 470], ['name' => 'Leafeon', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 471], ['name' => 'Glaceon', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 472], ['name' => 'Gliscor', 'primary' => 'Ground', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 473], ['name' => 'Mamoswine', 'primary' => 'Ice', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 474], ['name' => 'Porygon-Z', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 475], ['name' => 'Gallade', 'primary' => 'Psychic', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 476], ['name' => 'Probopass', 'primary' => 'Rock', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 477], ['name' => 'Dusknoir', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 478], ['name' => 'Froslass', 'primary' => 'Ice', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 479], ['name' => 'Rotom', 'primary' => 'Electric', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 480], ['name' => 'Uxie', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 481], ['name' => 'Mesprit', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 482], ['name' => 'Azelf', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 483], ['name' => 'Dialga', 'primary' => 'Steel', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 484], ['name' => 'Palkia', 'primary' => 'Water', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 485], ['name' => 'Heatran', 'primary' => 'Fire', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 486], ['name' => 'Regigigas', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 487], ['name' => 'Giratina', 'primary' => 'Ghost', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 488], ['name' => 'Cresselia', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 489], ['name' => 'Phione', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 490], ['name' => 'Manaphy', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 491], ['name' => 'Darkrai', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 492], ['name' => 'Shaymin', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 493], ['name' => 'Arceus', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 494], ['name' => 'Victini', 'primary' => 'Psychic', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 495], ['name' => 'Snivy', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 496], ['name' => 'Servine', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 497], ['name' => 'Serperior', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 498], ['name' => 'Tepig', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 499], ['name' => 'Pignite', 'primary' => 'Fire', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 500], ['name' => 'Emboar', 'primary' => 'Fire', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 501], ['name' => 'Oshawott', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 502], ['name' => 'Dewott', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 503], ['name' => 'Samurott', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 504], ['name' => 'Patrat', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 505], ['name' => 'Watchog', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 506], ['name' => 'Lillipup', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 507], ['name' => 'Herdier', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 508], ['name' => 'Stoutland', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 509], ['name' => 'Purrloin', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 510], ['name' => 'Liepard', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 511], ['name' => 'Pansage', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 512], ['name' => 'Simisage', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 513], ['name' => 'Pansear', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 514], ['name' => 'Simisear', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 515], ['name' => 'Panpour', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 516], ['name' => 'Simipour', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 517], ['name' => 'Munna', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 518], ['name' => 'Musharna', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 519], ['name' => 'Pidove', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 520], ['name' => 'Tranquill', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 521], ['name' => 'Unfezant', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 522], ['name' => 'Blitzle', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 523], ['name' => 'Zebstrika', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 524], ['name' => 'Roggenrola', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 525], ['name' => 'Boldore', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 526], ['name' => 'Gigalith', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 527], ['name' => 'Woobat', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 528], ['name' => 'Swoobat', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 529], ['name' => 'Drilbur', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 530], ['name' => 'Excadrill', 'primary' => 'Ground', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 531], ['name' => 'Audino', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 532], ['name' => 'Timburr', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 533], ['name' => 'Gurdurr', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 534], ['name' => 'Conkeldurr', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 535], ['name' => 'Tympole', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 536], ['name' => 'Palpitoad', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 537], ['name' => 'Seismitoad', 'primary' => 'Water', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 538], ['name' => 'Throh', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 539], ['name' => 'Sawk', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 540], ['name' => 'Sewaddle', 'primary' => 'Bug', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 541], ['name' => 'Swadloon', 'primary' => 'Bug', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 542], ['name' => 'Leavanny', 'primary' => 'Bug', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 543], ['name' => 'Venipede', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 544], ['name' => 'Whirlipede', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 545], ['name' => 'Scolipede', 'primary' => 'Bug', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 546], ['name' => 'Cottonee', 'primary' => 'Grass', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 547], ['name' => 'Whimsicott', 'primary' => 'Grass', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 548], ['name' => 'Petilil', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 549], ['name' => 'Lilligant', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 550], ['name' => 'Basculin', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 551], ['name' => 'Sandile', 'primary' => 'Ground', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 552], ['name' => 'Krokorok', 'primary' => 'Ground', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 553], ['name' => 'Krookodile', 'primary' => 'Ground', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 554], ['name' => 'Darumaka', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 555], ['name' => 'Darmanitan', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 556], ['name' => 'Maractus', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 557], ['name' => 'Dwebble', 'primary' => 'Bug', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 558], ['name' => 'Crustle', 'primary' => 'Bug', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 559], ['name' => 'Scraggy', 'primary' => 'Dark', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 560], ['name' => 'Scrafty', 'primary' => 'Dark', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 561], ['name' => 'Sigilyph', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 562], ['name' => 'Yamask', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 563], ['name' => 'Cofagrigus', 'primary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 564], ['name' => 'Tirtouga', 'primary' => 'Water', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 565], ['name' => 'Carracosta', 'primary' => 'Water', 'secondary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 566], ['name' => 'Archen', 'primary' => 'Rock', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 567], ['name' => 'Archeops', 'primary' => 'Rock', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 568], ['name' => 'Trubbish', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 569], ['name' => 'Garbodor', 'primary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 570], ['name' => 'Zorua', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 571], ['name' => 'Zoroark', 'primary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 572], ['name' => 'Minccino', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 573], ['name' => 'Cinccino', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 574], ['name' => 'Gothita', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 575], ['name' => 'Gothorita', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 576], ['name' => 'Gothitelle', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 577], ['name' => 'Solosis', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 578], ['name' => 'Duosion', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 579], ['name' => 'Reuniclus', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 580], ['name' => 'Ducklett', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 581], ['name' => 'Swanna', 'primary' => 'Water', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 582], ['name' => 'Vanillite', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 583], ['name' => 'Vanillish', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 584], ['name' => 'Vanilluxe', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 585], ['name' => 'Deerling', 'primary' => 'Normal', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 586], ['name' => 'Sawsbuck', 'primary' => 'Normal', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 587], ['name' => 'Emolga', 'primary' => 'Electric', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 588], ['name' => 'Karrablast', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 589], ['name' => 'Escavalier', 'primary' => 'Bug', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 590], ['name' => 'Foongus', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 591], ['name' => 'Amoonguss', 'primary' => 'Grass', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 592], ['name' => 'Frillish', 'primary' => 'Water', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 593], ['name' => 'Jellicent', 'primary' => 'Water', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 594], ['name' => 'Alomomola', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 595], ['name' => 'Joltik', 'primary' => 'Bug', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 596], ['name' => 'Galvantula', 'primary' => 'Bug', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 597], ['name' => 'Ferroseed', 'primary' => 'Grass', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 598], ['name' => 'Ferrothorn', 'primary' => 'Grass', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 599], ['name' => 'Klink', 'primary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 600], ['name' => 'Klang', 'primary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 601], ['name' => 'Klinklang', 'primary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 602], ['name' => 'Tynamo', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 603], ['name' => 'Eelektrik', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 604], ['name' => 'Eelektross', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 605], ['name' => 'Elgyem', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 606], ['name' => 'Beheeyem', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 607], ['name' => 'Litwick', 'primary' => 'Ghost', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 608], ['name' => 'Lampent', 'primary' => 'Ghost', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 609], ['name' => 'Chandelure', 'primary' => 'Ghost', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 610], ['name' => 'Axew', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 611], ['name' => 'Fraxure', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 612], ['name' => 'Haxorus', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 613], ['name' => 'Cubchoo', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 614], ['name' => 'Beartic', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 615], ['name' => 'Cryogonal', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 616], ['name' => 'Shelmet', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 617], ['name' => 'Accelgor', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 618], ['name' => 'Stunfisk', 'primary' => 'Ground', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 619], ['name' => 'Mienfoo', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 620], ['name' => 'Mienshao', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 621], ['name' => 'Druddigon', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 622], ['name' => 'Golett', 'primary' => 'Ground', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 623], ['name' => 'Golurk', 'primary' => 'Ground', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 624], ['name' => 'Pawniard', 'primary' => 'Dark', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 625], ['name' => 'Bisharp', 'primary' => 'Dark', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 626], ['name' => 'Bouffalant', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 627], ['name' => 'Rufflet', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 628], ['name' => 'Braviary', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 629], ['name' => 'Vullaby', 'primary' => 'Dark', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 630], ['name' => 'Mandibuzz', 'primary' => 'Dark', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 631], ['name' => 'Heatmor', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 632], ['name' => 'Durant', 'primary' => 'Bug', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 633], ['name' => 'Deino', 'primary' => 'Dark', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 634], ['name' => 'Zweilous', 'primary' => 'Dark', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 635], ['name' => 'Hydreigon', 'primary' => 'Dark', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 636], ['name' => 'Larvesta', 'primary' => 'Bug', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 637], ['name' => 'Volcarona', 'primary' => 'Bug', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 638], ['name' => 'Cobalion', 'primary' => 'Steel', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 639], ['name' => 'Terrakion', 'primary' => 'Rock', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 640], ['name' => 'Virizion', 'primary' => 'Grass', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 641], ['name' => 'Tornadus', 'primary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 642], ['name' => 'Thundurus', 'primary' => 'Electric', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 643], ['name' => 'Reshiram', 'primary' => 'Dragon', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 644], ['name' => 'Zekrom', 'primary' => 'Dragon', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 645], ['name' => 'Landorus', 'primary' => 'Ground', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 646], ['name' => 'Kyurem', 'primary' => 'Dragon', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 647], ['name' => 'Keldeo', 'primary' => 'Water', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 648], ['name' => 'Meloetta', 'primary' => 'Normal', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 649], ['name' => 'Genesect', 'primary' => 'Bug', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 650], ['name' => 'Chespin', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 651], ['name' => 'Quilladin', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 652], ['name' => 'Chesnaught', 'primary' => 'Grass', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 653], ['name' => 'Fennekin', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 654], ['name' => 'Braixen', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 655], ['name' => 'Delphox', 'primary' => 'Fire', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 656], ['name' => 'Froakie', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 657], ['name' => 'Frogadier', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 658], ['name' => 'Greninja', 'primary' => 'Water', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 659], ['name' => 'Bunnelby', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 660], ['name' => 'Diggersby', 'primary' => 'Normal', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 661], ['name' => 'Fletchling', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 662], ['name' => 'Fletchinder', 'primary' => 'Fire', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 663], ['name' => 'Talonflame', 'primary' => 'Fire', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 664], ['name' => 'Scatterbug', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 665], ['name' => 'Spewpa', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 666], ['name' => 'Vivillon', 'primary' => 'Bug', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 667], ['name' => 'Litleo', 'primary' => 'Fire', 'secondary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 668], ['name' => 'Pyroar', 'primary' => 'Fire', 'secondary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 669], ['name' => 'Flabébé', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 670], ['name' => 'Floette', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 671], ['name' => 'Florges', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 672], ['name' => 'Skiddo', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 673], ['name' => 'Gogoat', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 674], ['name' => 'Pancham', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 675], ['name' => 'Pangoro', 'primary' => 'Fighting', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 676], ['name' => 'Furfrou', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 677], ['name' => 'Espurr', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 678], ['name' => 'Meowstic', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 679], ['name' => 'Honedge', 'primary' => 'Steel', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 680], ['name' => 'Doublade', 'primary' => 'Steel', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 681], ['name' => 'Aegislash', 'primary' => 'Steel', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 682], ['name' => 'Spritzee', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 683], ['name' => 'Aromatisse', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 684], ['name' => 'Swirlix', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 685], ['name' => 'Slurpuff', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 686], ['name' => 'Inkay', 'primary' => 'Dark', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 687], ['name' => 'Malamar', 'primary' => 'Dark', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 688], ['name' => 'Binacle', 'primary' => 'Rock', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 689], ['name' => 'Barbaracle', 'primary' => 'Rock', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 690], ['name' => 'Skrelp', 'primary' => 'Poison', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 691], ['name' => 'Dragalge', 'primary' => 'Poison', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 692], ['name' => 'Clauncher', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 693], ['name' => 'Clawitzer', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 694], ['name' => 'Helioptile', 'primary' => 'Electric', 'secondary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 695], ['name' => 'Heliolisk', 'primary' => 'Electric', 'secondary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 696], ['name' => 'Tyrunt', 'primary' => 'Rock', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 697], ['name' => 'Tyrantrum', 'primary' => 'Rock', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 698], ['name' => 'Amaura', 'primary' => 'Rock', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 699], ['name' => 'Aurorus', 'primary' => 'Rock', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 700], ['name' => 'Sylveon', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 701], ['name' => 'Hawlucha', 'primary' => 'Fighting', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 702], ['name' => 'Dedenne', 'primary' => 'Electric', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 703], ['name' => 'Carbink', 'primary' => 'Rock', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 704], ['name' => 'Goomy', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 705], ['name' => 'Sliggoo', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 706], ['name' => 'Goodra', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 707], ['name' => 'Klefki', 'primary' => 'Steel', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 708], ['name' => 'Phantump', 'primary' => 'Ghost', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 709], ['name' => 'Trevenant', 'primary' => 'Ghost', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 710], ['name' => 'Pumpkaboo', 'primary' => 'Ghost', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 711], ['name' => 'Gourgeist', 'primary' => 'Ghost', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 712], ['name' => 'Bergmite', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 713], ['name' => 'Avalugg', 'primary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 714], ['name' => 'Noibat', 'primary' => 'Flying', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 715], ['name' => 'Noivern', 'primary' => 'Flying', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 716], ['name' => 'Xerneas', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 717], ['name' => 'Yveltal', 'primary' => 'Dark', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 718], ['name' => 'Zygarde', 'primary' => 'Dragon', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 719], ['name' => 'Diancie', 'primary' => 'Rock', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 720], ['name' => 'Hoopa', 'primary' => 'Psychic', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 721], ['name' => 'Volcanion', 'primary' => 'Fire', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 722], ['name' => 'Rowlet', 'primary' => 'Grass', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 723], ['name' => 'Dartrix', 'primary' => 'Grass', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 724], ['name' => 'Decidueye', 'primary' => 'Grass', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 725], ['name' => 'Litten', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 726], ['name' => 'Torracat', 'primary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 727], ['name' => 'Incineroar', 'primary' => 'Fire', 'secondary' => 'Dark',]);
        Pokemon::updateOrCreate(['id' => 728], ['name' => 'Popplio', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 729], ['name' => 'Brionne', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 730], ['name' => 'Primarina', 'primary' => 'Water', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 731], ['name' => 'Pikipek', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 732], ['name' => 'Trumbeak', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 733], ['name' => 'Toucannon', 'primary' => 'Normal', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 734], ['name' => 'Yungoos', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 735], ['name' => 'Gumshoos', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 736], ['name' => 'Grubbin', 'primary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 737], ['name' => 'Charjabug', 'primary' => 'Bug', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 738], ['name' => 'Vikavolt', 'primary' => 'Bug', 'secondary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 739], ['name' => 'Crabrawler', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 740], ['name' => 'Crabominable', 'primary' => 'Fighting', 'secondary' => 'Ice',]);
        Pokemon::updateOrCreate(['id' => 741.1], ['name' => 'Oricorio (Baile)', 'primary' => 'Fire', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 741.2], ['name' => 'Oricorio (P\'au)', 'primary' => 'Psychic', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 741.3], ['name' => 'Oricorio (Pom-Pom)', 'primary' => 'Electric', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 741.4], ['name' => 'Oricorio (Sensu)', 'primary' => 'Ghost', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 742], ['name' => 'Cutiefly', 'primary' => 'Bug', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 743], ['name' => 'Ribombee', 'primary' => 'Bug', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 744], ['name' => 'Rockruff', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 745], ['name' => 'Lycanroc: Midday', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 745], ['name' => 'Lycanroc: Midnight', 'primary' => 'Rock',]);
        Pokemon::updateOrCreate(['id' => 746], ['name' => 'Wishiwashi: Solo', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 746], ['name' => 'Wishiwashi: Schooling', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 747], ['name' => 'Mareanie', 'primary' => 'Poison', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 748], ['name' => 'Toxapex', 'primary' => 'Poison', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 749], ['name' => 'Mudbray', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 750], ['name' => 'Mudsdale', 'primary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 751], ['name' => 'Dewpider', 'primary' => 'Water', 'secondary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 752], ['name' => 'Araquanid', 'primary' => 'Water', 'secondary' => 'Bug',]);
        Pokemon::updateOrCreate(['id' => 753], ['name' => 'Fomantis', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 754], ['name' => 'Lurantis', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 755], ['name' => 'Morelull', 'primary' => 'Grass', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 756], ['name' => 'Shiinotic', 'primary' => 'Grass', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 757], ['name' => 'Salandit', 'primary' => 'Poison', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 758], ['name' => 'Salazzle', 'primary' => 'Poison', 'secondary' => 'Fire',]);
        Pokemon::updateOrCreate(['id' => 759], ['name' => 'Stufful', 'primary' => 'Normal', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 760], ['name' => 'Bewear', 'primary' => 'Normal', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 761], ['name' => 'Bounsweet', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 762], ['name' => 'Steenee', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 763], ['name' => 'Tsareena', 'primary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 764], ['name' => 'Comfey', 'primary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 765], ['name' => 'Oranguru', 'primary' => 'Normal', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 766], ['name' => 'Passimian', 'primary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 767], ['name' => 'Wimpod', 'primary' => 'Bug', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 768], ['name' => 'Golisopod', 'primary' => 'Bug', 'secondary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 769], ['name' => 'Sandygast', 'primary' => 'Ghost', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 770], ['name' => 'Palossand', 'primary' => 'Ghost', 'secondary' => 'Ground',]);
        Pokemon::updateOrCreate(['id' => 771], ['name' => 'Pyukumuku', 'primary' => 'Water',]);
        Pokemon::updateOrCreate(['id' => 772], ['name' => 'Type: Null', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 773], ['name' => 'Silvally', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 774], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 774.1], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Blue Core',]);
        Pokemon::updateOrCreate(['id' => 774.2], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Green Core',]);
        Pokemon::updateOrCreate(['id' => 774.3], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Indigo Core',]);
        Pokemon::updateOrCreate(['id' => 774.4], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Orange Core',]);
        Pokemon::updateOrCreate(['id' => 774.5], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Red Core',]);
        Pokemon::updateOrCreate(['id' => 774.6], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Violet Core',]);
        Pokemon::updateOrCreate(['id' => 774.7], ['name' => 'Minior', 'primary' => 'Rock', 'secondary' => 'Flying', 'variant' => 'Yellow Core',]); 
        Pokemon::updateOrCreate(['id' => 775], ['name' => 'Komala', 'primary' => 'Normal',]);
        Pokemon::updateOrCreate(['id' => 776], ['name' => 'Turtonator', 'primary' => 'Fire', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 777], ['name' => 'Togedemaru', 'primary' => 'Electric', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 778], ['name' => 'Mimikyu', 'primary' => 'Ghost', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 779], ['name' => 'Bruxish', 'primary' => 'Water', 'secondary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 780], ['name' => 'Drampa', 'primary' => 'Normal', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 781], ['name' => 'Dhelmise', 'primary' => 'Ghost', 'secondary' => 'Grass',]);
        Pokemon::updateOrCreate(['id' => 782], ['name' => 'Jangmo-o', 'primary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 783], ['name' => 'Hakamo-o', 'primary' => 'Dragon', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 784], ['name' => 'Kommo-o', 'primary' => 'Dragon', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 785], ['name' => 'Tapu Koko', 'primary' => 'Electric', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 786], ['name' => 'Tapu Lele', 'primary' => 'Psychic', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 787], ['name' => 'Tapu Bulu', 'primary' => 'Grass', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 788], ['name' => 'Tapu Fini', 'primary' => 'Water', 'secondary' => 'Fairy',]);
        Pokemon::updateOrCreate(['id' => 789], ['name' => 'Cosmog', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 790], ['name' => 'Cosmoem', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 791], ['name' => 'Solgaleo', 'primary' => 'Psychic', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 792], ['name' => 'Lunala', 'primary' => 'Psychic', 'secondary' => 'Ghost',]);
        Pokemon::updateOrCreate(['id' => 793], ['name' => 'Nihilego', 'primary' => 'Rock', 'secondary' => 'Poison',]);
        Pokemon::updateOrCreate(['id' => 794], ['name' => 'Buzzwole', 'primary' => 'Bug', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 795], ['name' => 'Pheromosa', 'primary' => 'Bug', 'secondary' => 'Fighting',]);
        Pokemon::updateOrCreate(['id' => 796], ['name' => 'Xurkitree', 'primary' => 'Electric',]);
        Pokemon::updateOrCreate(['id' => 797], ['name' => 'Celesteela', 'primary' => 'Steel', 'secondary' => 'Flying',]);
        Pokemon::updateOrCreate(['id' => 798], ['name' => 'Kartana', 'primary' => 'Grass', 'secondary' => 'Steel',]);
        Pokemon::updateOrCreate(['id' => 799], ['name' => 'Guzzlord', 'primary' => 'Dark', 'secondary' => 'Dragon',]);
        Pokemon::updateOrCreate(['id' => 800], ['name' => 'Necrozma', 'primary' => 'Psychic',]);
        Pokemon::updateOrCreate(['id' => 801], ['name' => 'Magearna', 'primary' => 'Steel', 'secondary' => 'Fairy',]);
    }
}
